class Constants{
    TITLE="Swag Labs";
    INVENTORY_PAGE_HEADER="PRODUCTS";
    CART_PAGE_HEADER="YOUR CART";
    CHECKOUT_PAGE_HEADER="CHECKOUT: YOUR INFORMATION";
    FINISH_PAGE_HEADER="CHECKOUT: OVERVIEW";
    SUCCESS_MSG="THANK YOU FOR YOUR ORDER";
}
module.exports=new Constants();
